/**
 * Luna Dream — screenshot captions per copy language.
 * Source: vault «ASO Audit — 2026-09-25» §8 (EN/RU table + market variants).
 * Frame keys: result, voice, interp, symbol, chat, image, insights → [headline, subline].
 * `symbol` already carries the market variant (Islamic / Zhou Gong / Vedic / RU).
 * Only verifiable facts: no prices, no "free", no rankings.
 */
export const COPY = {
  en: {
    result: ['What did your dream mean?', 'AI interpretation in seconds'],
    voice: ['Just say it when you wake up', 'Voice or text — every dream is saved'],
    interp: ['A reading made for you', 'Emotions, symbols and the message behind them'],
    symbol: ['300+ dream symbols', 'Islamic (Ibn Sirin), Jungian, folk and more traditions'],
    chat: ['Talk it through with Luna', 'Ask anything about your dream'],
    image: ['See your dream', 'Turn any dream into a picture'],
    insights: ['Find your patterns', 'Recurring symbols and moods. Private, Face ID lock'],
  },
  ru: {
    result: ['К чему этот сон?', 'Толкование от AI за секунды'],
    voice: ['Просто расскажите сон', 'Голосом или текстом — каждый сон сохранится'],
    interp: ['Толкование лично для вас', 'Эмоции, символы и их смысл'],
    symbol: ['300+ символов сонника', 'Исламский (Ибн Сирин) и народный сонник, толкование по Юнгу'],
    chat: ['Обсудите сон с Луной', 'Задайте любой вопрос о своём сне'],
    image: ['Увидьте свой сон', 'Картинка по вашему описанию'],
    insights: ['Найдите закономерности', 'Повторяющиеся символы и настроения. Вход по Face ID'],
  },
  uk: {
    result: ['Що означав ваш сон?', 'Тлумачення від ШІ за лічені секунди'],
    voice: ['Розкажіть свій сон', 'Голосом чи текстом — кожен сон збережеться'],
    interp: ['Тлумачення саме для вас', 'Емоції, символи та їхній зміст'],
    symbol: ['300+ символів сонника', 'Ісламський (Ібн Сірін) і народний сонник, тлумачення за Юнгом'],
    chat: ['Обговоріть сон з Луною', 'Поставте будь-яке запитання про свій сон'],
    image: ['Побачте свій сон', 'Картинка за вашим описом'],
    insights: ['Знайдіть закономірності', 'Символи та настрої, що повторюються. Вхід за Face ID'],
  },
  de: {
    result: ['Was bedeutet dein Traum?', 'KI-Deutung in Sekunden'],
    voice: ['Morgens einfach erzählen', 'Per Stimme oder Text — jeder Traum wird gespeichert'],
    interp: ['Eine Deutung nur für dich', 'Gefühle, Symbole und ihre Botschaft'],
    symbol: ['300+ Traumsymbole', 'Islamische (Ibn Sirin), jungsche, volkstümliche Deutung und mehr'],
    chat: ['Sprich mit Luna darüber', 'Frag alles zu deinem Traum'],
    image: ['Sieh deinen Traum', 'Mach aus jedem Traum ein Bild'],
    insights: ['Erkenne deine Muster', 'Wiederkehrende Symbole und Stimmungen. Privat, mit Face ID'],
  },
  fr: {
    result: ['Que signifie votre rêve ?', 'Interprétation par IA en quelques secondes'],
    voice: ['Racontez-le dès le réveil', 'À voix haute ou par écrit — chaque rêve est gardé'],
    interp: ['Une lecture rien que pour vous', 'Émotions, symboles et leur message'],
    symbol: ['300+ symboles de rêves', 'Traditions islamique (Ibn Sirin), jungienne, populaire et d’autres'],
    chat: ['Parlez-en avec Luna', 'Posez toutes vos questions sur votre rêve'],
    image: ['Voyez votre rêve', 'Transformez chaque rêve en image'],
    insights: ['Découvrez vos schémas', 'Symboles et humeurs récurrents. Privé, verrouillé par Face ID'],
  },
  es: {
    result: ['¿Qué significa tu sueño?', 'Interpretación con IA en segundos'],
    voice: ['Cuéntalo al despertar', 'Por voz o texto: cada sueño queda guardado'],
    interp: ['Una lectura hecha para ti', 'Emociones, símbolos y su mensaje'],
    symbol: ['Más de 300 símbolos', 'Tradición islámica (Ibn Sirin), junguiana, popular y más'],
    chat: ['Háblalo con Luna', 'Pregunta lo que quieras sobre tu sueño'],
    image: ['Mira tu sueño', 'Convierte cualquier sueño en una imagen'],
    insights: ['Descubre tus patrones', 'Símbolos y estados de ánimo que se repiten. Privado, con Face ID'],
  },
  ca: {
    result: ['Què vol dir el teu somni?', 'Interpretació amb IA en segons'],
    voice: ['Explica’l en despertar', 'Amb la veu o per escrit: cada somni queda desat'],
    interp: ['Una lectura feta per a tu', 'Emocions, símbols i el seu missatge'],
    symbol: ['Més de 300 símbols', 'Tradició islàmica (Ibn Sirin), junguiana, popular i més'],
    chat: ['Parla’n amb la Luna', 'Pregunta el que vulguis del teu somni'],
    image: ['Mira el teu somni', 'Converteix qualsevol somni en una imatge'],
    insights: ['Descobreix els teus patrons', 'Símbols i estats d’ànim que es repeteixen. Privat, amb Face ID'],
  },
  it: {
    result: ['Cosa significa il tuo sogno?', 'Interpretazione con IA in pochi secondi'],
    voice: ['Raccontalo appena sveglio', 'A voce o per iscritto: ogni sogno resta salvato'],
    interp: ['Un’interpretazione tutta per te', 'Emozioni, simboli e il loro messaggio'],
    symbol: ['Oltre 300 simboli', 'Tradizione islamica (Ibn Sirin), junghiana, popolare e altre'],
    chat: ['Parlane con Luna', 'Chiedi qualsiasi cosa sul tuo sogno'],
    image: ['Guarda il tuo sogno', 'Trasforma ogni sogno in un’immagine'],
    insights: ['Scopri i tuoi schemi', 'Simboli e stati d’animo ricorrenti. Privato, con Face ID'],
  },
  'pt-BR': {
    result: ['O que seu sonho significa?', 'Interpretação com IA em segundos'],
    voice: ['Conte assim que acordar', 'Por voz ou texto — cada sonho fica salvo'],
    interp: ['Uma leitura feita para você', 'Emoções, símbolos e a mensagem por trás deles'],
    symbol: ['Mais de 300 símbolos', 'Tradição islâmica (Ibn Sirin), junguiana, popular e outras'],
    chat: ['Converse com a Luna', 'Pergunte o que quiser sobre seu sonho'],
    image: ['Veja seu sonho', 'Transforme qualquer sonho em imagem'],
    insights: ['Descubra seus padrões', 'Símbolos e humores recorrentes. Privado, com Face ID'],
  },
  'pt-PT': {
    result: ['O que significa o seu sonho?', 'Interpretação com IA em segundos'],
    voice: ['Conte-o assim que acordar', 'Por voz ou texto — cada sonho fica guardado'],
    interp: ['Uma leitura feita para si', 'Emoções, símbolos e a mensagem por trás deles'],
    symbol: ['Mais de 300 símbolos', 'Tradição islâmica (Ibn Sirin), junguiana, popular e outras'],
    chat: ['Fale sobre ele com a Luna', 'Pergunte o que quiser sobre o seu sonho'],
    image: ['Veja o seu sonho', 'Transforme qualquer sonho numa imagem'],
    insights: ['Descubra os seus padrões', 'Símbolos e estados de espírito recorrentes. Privado, com Face ID'],
  },
  nl: {
    result: ['Wat betekent je droom?', 'AI-duiding in seconden'],
    voice: ['Vertel hem bij het ontwaken', 'Met je stem of als tekst — elke droom wordt bewaard'],
    interp: ['Een duiding speciaal voor jou', 'Emoties, symbolen en hun boodschap'],
    symbol: ['300+ droomsymbolen', 'Islamitische (Ibn Sirin), jungiaanse, volkse en meer tradities'],
    chat: ['Praat erover met Luna', 'Vraag alles over je droom'],
    image: ['Zie je droom', 'Maak van elke droom een beeld'],
    insights: ['Ontdek je patronen', 'Terugkerende symbolen en stemmingen. Privé, met Face ID'],
  },
  sv: {
    result: ['Vad betydde din dröm?', 'AI-tolkning på några sekunder'],
    voice: ['Berätta direkt när du vaknar', 'Med rösten eller i text — varje dröm sparas'],
    interp: ['En tolkning just för dig', 'Känslor, symboler och deras budskap'],
    symbol: ['300+ drömsymboler', 'Islamisk (Ibn Sirin), jungiansk, folklig och fler traditioner'],
    chat: ['Prata om den med Luna', 'Fråga vad du vill om din dröm'],
    image: ['Se din dröm', 'Gör en bild av vilken dröm som helst'],
    insights: ['Hitta dina mönster', 'Återkommande symboler och stämningar. Privat, med Face ID'],
  },
  da: {
    result: ['Hvad betød din drøm?', 'AI-tydning på få sekunder'],
    voice: ['Fortæl den, når du vågner', 'Med stemmen eller i tekst — hver drøm gemmes'],
    interp: ['En tydning lavet til dig', 'Følelser, symboler og deres budskab'],
    symbol: ['300+ drømmesymboler', 'Islamisk (Ibn Sirin), jungiansk, folkelig og flere traditioner'],
    chat: ['Snak den igennem med Luna', 'Spørg om alt i din drøm'],
    image: ['Se din drøm', 'Gør enhver drøm til et billede'],
    insights: ['Find dine mønstre', 'Tilbagevendende symboler og stemninger. Privat, med Face ID'],
  },
  no: {
    result: ['Hva betydde drømmen din?', 'AI-tydning på sekunder'],
    voice: ['Fortell den når du våkner', 'Med stemmen eller i tekst — hver drøm lagres'],
    interp: ['En tydning laget for deg', 'Følelser, symboler og budskapet bak dem'],
    symbol: ['300+ drømmesymboler', 'Islamsk (Ibn Sirin), jungiansk, folkelig og flere tradisjoner'],
    chat: ['Snakk om den med Luna', 'Spør om alt i drømmen din'],
    image: ['Se drømmen din', 'Gjør hvilken som helst drøm til et bilde'],
    insights: ['Finn mønstrene dine', 'Gjentakende symboler og stemninger. Privat, med Face ID'],
  },
  fi: {
    result: ['Mitä unesi tarkoitti?', 'Tekoälyn tulkinta sekunneissa'],
    voice: ['Kerro se heti herättyäsi', 'Puhuen tai kirjoittaen — jokainen uni tallentuu'],
    interp: ['Tulkinta juuri sinulle', 'Tunteet, symbolit ja niiden viesti'],
    symbol: ['Yli 300 unisymbolia', 'Islamilainen (Ibn Sirin), jungilainen, kansanperinne ja muita'],
    chat: ['Juttele siitä Lunan kanssa', 'Kysy unestasi mitä vain'],
    image: ['Näe unesi', 'Muuta mikä tahansa uni kuvaksi'],
    insights: ['Löydä toistuvat kuviot', 'Toistuvat symbolit ja tunnelmat. Yksityinen, Face ID -lukitus'],
  },
  pl: {
    result: ['Co oznaczał twój sen?', 'Interpretacja AI w kilka sekund'],
    voice: ['Opowiedz go po przebudzeniu', 'Głosem lub tekstem — każdy sen zostaje zapisany'],
    interp: ['Interpretacja dla ciebie', 'Emocje, symbole i ich przesłanie'],
    symbol: ['Ponad 300 symboli', 'Tradycja islamska (Ibn Sirin), jungowska, ludowa i inne'],
    chat: ['Porozmawiaj o nim z Luną', 'Zapytaj o wszystko, co dotyczy snu'],
    image: ['Zobacz swój sen', 'Zamień każdy sen w obraz'],
    insights: ['Odkryj swoje wzorce', 'Powracające symbole i nastroje. Prywatnie, blokada Face ID'],
  },
  cs: {
    result: ['Co znamenal tvůj sen?', 'Výklad pomocí AI během pár sekund'],
    voice: ['Řekni ho hned po probuzení', 'Hlasem nebo textem — každý sen se uloží'],
    interp: ['Výklad přímo pro tebe', 'Emoce, symboly a jejich poselství'],
    symbol: ['Přes 300 symbolů snů', 'Islámský (Ibn Sírín), jungiánský, lidový výklad a další'],
    chat: ['Probírej ho s Lunou', 'Zeptej se na cokoli o svém snu'],
    image: ['Uvidíš svůj sen', 'Proměň jakýkoli sen v obrázek'],
    insights: ['Najdi své vzorce', 'Opakující se symboly a nálady. Soukromé, zámek Face ID'],
  },
  sk: {
    result: ['Čo znamenal tvoj sen?', 'Výklad pomocou AI za pár sekúnd'],
    voice: ['Povedz ho hneď po prebudení', 'Hlasom alebo textom — každý sen sa uloží'],
    interp: ['Výklad priamo pre teba', 'Emócie, symboly a ich posolstvo'],
    symbol: ['Viac ako 300 symbolov', 'Islamský (Ibn Sírín), jungovský, ľudový výklad a ďalšie'],
    chat: ['Preber ho s Lunou', 'Opýtaj sa na čokoľvek o svojom sne'],
    image: ['Uvidíš svoj sen', 'Premeň akýkoľvek sen na obrázok'],
    insights: ['Nájdi svoje vzorce', 'Opakujúce sa symboly a nálady. Súkromné, zámok Face ID'],
  },
  hu: {
    result: ['Mit jelentett az álmod?', 'MI-alapú álomfejtés másodpercek alatt'],
    voice: ['Mondd el, amint felébredsz', 'Hanggal vagy szövegben — minden álmod megmarad'],
    interp: ['Neked szóló álomfejtés', 'Érzelmek, szimbólumok és üzenetük'],
    symbol: ['Több mint 300 álomszimbólum', 'Iszlám (Ibn Szírín), jungi, népi és más hagyományok'],
    chat: ['Beszéld meg Lunával', 'Kérdezz bármit az álmodról'],
    image: ['Lásd az álmodat', 'Bármely álmodból kép lesz'],
    insights: ['Ismerd fel a mintáidat', 'Visszatérő szimbólumok és hangulatok. Privát, Face ID-zár'],
  },
  ro: {
    result: ['Ce înseamnă visul tău?', 'Interpretare AI în câteva secunde'],
    voice: ['Spune-l imediat ce te trezești', 'Cu vocea sau în scris — fiecare vis e salvat'],
    interp: ['O interpretare doar pentru tine', 'Emoții, simboluri și mesajul lor'],
    symbol: ['Peste 300 de simboluri', 'Tradiția islamică (Ibn Sirin), jungiană, populară și altele'],
    chat: ['Discută-l cu Luna', 'Întreabă orice despre visul tău'],
    image: ['Vezi-ți visul', 'Transformă orice vis într-o imagine'],
    insights: ['Descoperă tiparele', 'Simboluri și stări care revin. Privat, cu Face ID'],
  },
  hr: {
    result: ['Što je značio tvoj san?', 'Tumačenje uz AI za nekoliko sekundi'],
    voice: ['Ispričaj ga čim se probudiš', 'Glasom ili tekstom — svaki san ostaje spremljen'],
    interp: ['Tumačenje samo za tebe', 'Emocije, simboli i njihova poruka'],
    symbol: ['Više od 300 simbola', 'Islamska (Ibn Sirin), jungovska, narodna i druge tradicije'],
    chat: ['Porazgovaraj s Lunom', 'Pitaj bilo što o svom snu'],
    image: ['Pogledaj svoj san', 'Pretvori bilo koji san u sliku'],
    insights: ['Otkrij svoje obrasce', 'Simboli i raspoloženja koji se ponavljaju. Privatno, uz Face ID'],
  },
  'sl-SI': {
    result: ['Kaj je pomenil tvoj sen?', 'Razlaga z UI v nekaj sekundah'],
    voice: ['Povej ga takoj, ko se zbudiš', 'Z glasom ali besedilom — vsak sen se shrani'],
    interp: ['Razlaga samo zate', 'Čustva, simboli in njihovo sporočilo'],
    symbol: ['Več kot 300 simbolov', 'Islamska (Ibn Sirin), jungovska, ljudska in druge tradicije'],
    chat: ['Pogovori se z Luno', 'Vprašaj karkoli o svojem snu'],
    image: ['Poglej svoj sen', 'Vsak sen spremeni v sliko'],
    insights: ['Odkrij svoje vzorce', 'Simboli in razpoloženja, ki se ponavljajo. Zasebno, s Face ID'],
  },
  el: {
    result: ['Τι σήμαινε το όνειρό σου;', 'Ερμηνεία με AI σε δευτερόλεπτα'],
    voice: ['Πες το μόλις ξυπνήσεις', 'Με φωνή ή κείμενο — κάθε όνειρο αποθηκεύεται'],
    interp: ['Μια ερμηνεία μόνο για σένα', 'Συναισθήματα, σύμβολα και το μήνυμά τους'],
    symbol: ['300+ σύμβολα ονείρων', 'Ισλαμική (Ιμπν Σιρίν), γιουνγκιανή, λαϊκή παράδοση και άλλες'],
    chat: ['Συζήτησέ το με τη Luna', 'Ρώτα ό,τι θέλεις για το όνειρό σου'],
    image: ['Δες το όνειρό σου', 'Κάνε κάθε όνειρο εικόνα'],
    insights: ['Βρες τα μοτίβα σου', 'Σύμβολα και διαθέσεις που επανέρχονται. Ιδιωτικό, με Face ID'],
  },
  vi: {
    result: ['Giấc mơ của bạn có ý nghĩa gì?', 'Giải mã bằng AI chỉ trong vài giây'],
    voice: ['Kể ngay khi vừa thức dậy', 'Bằng giọng nói hoặc văn bản — mọi giấc mơ đều được lưu'],
    interp: ['Lời giải\ncho riêng bạn', 'Cảm xúc, biểu tượng và thông điệp ẩn sau'],
    symbol: ['Hơn 300 biểu tượng', 'Hồi giáo (Ibn Sirin), Jung, dân gian và nhiều truyền thống khác'],
    chat: ['Trò chuyện cùng Luna', 'Hỏi mọi điều về giấc mơ của bạn'],
    image: ['Thấy giấc mơ\ncủa bạn', 'Biến mọi giấc mơ thành hình ảnh'],
    insights: ['Tìm ra\nquy luật của bạn', 'Biểu tượng và tâm trạng lặp lại. Riêng tư, khóa bằng Face ID'],
  },
  th: {
    result: ['ฝันของคุณหมายถึงอะไร', 'ทำนายด้วย AI ในไม่กี่วินาที'],
    voice: ['ตื่นมาก็เล่าได้ทันที', 'พูดหรือพิมพ์ — ทุกความฝันถูกบันทึกไว้'],
    interp: ['คำทำนายเพื่อคุณโดยเฉพาะ', 'อารมณ์ สัญลักษณ์ และความหมายที่ซ่อนอยู่'],
    symbol: ['สัญลักษณ์ความฝัน 300+', 'อิสลาม (อิบนุ ซีรีน) ยุง\nพื้นบ้าน และอีกหลายตำรา'],
    chat: ['คุยเรื่องฝันกับลูน่า', 'ถามอะไรก็ได้เกี่ยวกับความฝันของคุณ'],
    image: ['เห็นความฝันของคุณ', 'เปลี่ยนทุกความฝันให้เป็นภาพ'],
    insights: ['ค้นพบรูปแบบของคุณ', 'สัญลักษณ์และอารมณ์ที่เกิดซ้ำ\nเป็นส่วนตัว ล็อกด้วย Face ID'],
  },
  he: {
    result: ['מה החלום שלך אומר?', 'פירוש בעזרת AI תוך שניות'],
    voice: ['פשוט לספר כשמתעוררים', 'בקול או בכתב — כל חלום נשמר'],
    interp: ['פירוש שנכתב בשבילך', 'רגשות, סמלים והמסר שמאחוריהם'],
    symbol: ['מעל 300 סמלי חלום', 'מסורת אסלאמית (אבן סירין), יונגיאנית, עממית ועוד'],
    chat: ['לדבר על זה עם לונה', 'אפשר לשאול כל דבר על החלום'],
    image: ['לראות את החלום', 'כל חלום הופך לתמונה'],
    insights: ['לגלות דפוסים', 'סמלים ומצבי רוח חוזרים. פרטי, נעילה עם Face ID'],
  },
  // ── Tradition-first markets (symbol frame moves to position 2) ─────────
  ar: {
    result: ['ماذا يعني حلمك؟', 'تفسير بالذكاء الاصطناعي في ثوانٍ'],
    voice: ['احكِ حلمك فور استيقاظك', 'بالصوت أو بالكتابة — يُحفظ كل حلم'],
    interp: ['تفسير مخصص لك', 'المشاعر والرموز والرسالة التي تحملها'],
    symbol: ['تفسير ابن سيرين لكل رمز', 'أكثر من 300 رمز، مع تفسير يونغ والتفسير الشعبي'],
    chat: ['تحدّث مع لونا عن حلمك', 'اسأل أي شيء عن حلمك'],
    image: ['شاهد حلمك', 'حوّل أي حلم إلى صورة'],
    insights: ['اكتشف أنماطك', 'رموز ومشاعر متكررة. خاص، مع قفل Face ID'],
  },
  tr: {
    result: ['Rüyan ne anlama geliyor?', 'Yapay zekâ ile saniyeler içinde tabir'],
    voice: ['Uyanır uyanmaz anlat', 'Sesle ya da yazarak — her rüya kaydedilir'],
    interp: ['Sana özel bir yorum', 'Duygular, semboller ve ardındaki mesaj'],
    symbol: ['Her sembolde İslami tabir', '300+ sembol: İbn-i Sîrîn, Jung ve halk yorumları'],
    chat: ['Luna ile konuş', 'Rüyanla ilgili her şeyi sor'],
    image: ['Rüyanı gör', 'Her rüyayı bir resme dönüştür'],
    insights: ['Kalıplarını keşfet', 'Tekrarlayan semboller ve ruh halleri. Gizli, Face ID kilidi'],
  },
  ur: {
    result: ['آپ کے خواب کا کیا مطلب ہے؟', 'AI سے چند سیکنڈ میں تعبیر'],
    voice: ['جاگتے ہی بتا دیں', 'آواز یا تحریر — ہر خواب محفوظ رہتا ہے'],
    interp: ['خاص آپ کے لیے تعبیر', 'جذبات، علامتیں اور ان کا پیغام'],
    symbol: ['ہر علامت کی اسلامی تعبیر', 'ابن سیرین کے مطابق 300 سے زائد علامتیں، ساتھ یونگ اور لوک تعبیر'],
    chat: ['لونا سے بات کریں', 'اپنے خواب کے بارے میں کچھ بھی پوچھیں'],
    image: ['اپنا خواب دیکھیں', 'کسی بھی خواب کو تصویر میں بدلیں'],
    insights: ['اپنے پیٹرن پہچانیں', 'بار بار آنے والی علامتیں اور کیفیات۔ نجی، Face ID لاک'],
  },
  bn: {
    result: ['আপনার স্বপ্নের মানে কী?', 'AI দিয়ে কয়েক সেকেন্ডে ব্যাখ্যা'],
    voice: ['ঘুম ভাঙলেই বলে ফেলুন', 'কণ্ঠে বা লিখে — প্রতিটি স্বপ্ন সংরক্ষিত থাকে'],
    interp: ['শুধু আপনার জন্য ব্যাখ্যা', 'আবেগ, প্রতীক আর তাদের বার্তা'],
    symbol: ['প্রতিটি প্রতীকের ইসলামি ব্যাখ্যা', 'ইবনে সিরিনের মতে ৩০০+ প্রতীক, সঙ্গে ইয়ুং ও লোকজ ব্যাখ্যা'],
    chat: ['লুনার সঙ্গে কথা বলুন', 'আপনার স্বপ্ন নিয়ে যা খুশি জিজ্ঞেস করুন'],
    image: ['আপনার স্বপ্ন দেখুন', 'যেকোনো স্বপ্নকে ছবিতে বদলে দিন'],
    insights: ['নিজের প্যাটার্ন খুঁজুন', 'বারবার আসা প্রতীক ও মেজাজ। ব্যক্তিগত, Face ID লক'],
  },
  id: {
    result: ['Apa arti mimpimu?', 'Tafsir AI dalam hitungan detik'],
    voice: ['Ceritakan begitu bangun', 'Lewat suara atau teks — setiap mimpi tersimpan'],
    interp: ['Tafsir khusus untukmu', 'Emosi, simbol, dan pesan di baliknya'],
    symbol: ['Tafsir Islami tiap simbol', '300+ simbol menurut Ibnu Sirin, plus tafsir Jung dan tradisi rakyat'],
    chat: ['Bahas bersama Luna', 'Tanyakan apa saja tentang mimpimu'],
    image: ['Lihat mimpimu', 'Ubah mimpi apa pun jadi gambar'],
    insights: ['Temukan polamu', 'Simbol dan suasana hati yang berulang. Privat, kunci Face ID'],
  },
  ms: {
    result: ['Apakah maksud mimpi anda?', 'Tafsiran AI dalam beberapa saat'],
    voice: ['Ceritakan sebaik bangun', 'Melalui suara atau teks — setiap mimpi disimpan'],
    interp: ['Tafsiran khas untuk anda', 'Emosi, simbol dan mesej di sebaliknya'],
    symbol: ['Tafsiran Islam bagi setiap simbol', '300+ simbol menurut Ibnu Sirin, serta tafsiran Jung dan rakyat'],
    chat: ['Bincang dengan Luna', 'Tanya apa sahaja tentang mimpi anda'],
    image: ['Lihat mimpi anda', 'Jadikan mana-mana mimpi sebuah gambar'],
    insights: ['Kenali corak anda', 'Simbol dan emosi yang berulang. Peribadi, kunci Face ID'],
  },
  // ── CJK: explicit breaks keep words whole on the headline ──────────────
  ja: {
    result: ['その夢、\nどんな意味？', 'AIが数秒で夢を解釈'],
    voice: ['起きたら話すだけ', '声でも文字でも、\n夢はすべて保存'],
    interp: ['あなただけの\n夢解釈', '感情、シンボル、\nそこに込められたメッセージ'],
    symbol: ['300以上の\n夢シンボル', 'イスラム（イブン・シーリーン）、\nユング、民間伝承など'],
    chat: ['ルナと語り合おう', '夢のことを何でも質問'],
    image: ['夢を絵で見る', 'どんな夢もイメージに'],
    insights: ['あなたの\nパターンを発見', '繰り返すシンボルと気分。\nFace IDでロック'],
  },
  ko: {
    result: ['꿈의 의미가\n궁금하세요?', 'AI가 몇 초 만에 해몽'],
    voice: ['일어나자마자\n말하세요', '음성이나 텍스트로 —\n모든 꿈이 저장돼요'],
    interp: ['나만을 위한\n꿈 해석', '감정, 상징,\n그리고 그 속의 메시지'],
    symbol: ['300개 이상의\n꿈 상징', '이슬람(이븐 시린), 융,\n민간 해몽 등 다양한 전통'],
    chat: ['루나와\n이야기해 보세요', '꿈에 대해\n무엇이든 물어보세요'],
    image: ['꿈을 그림으로', '어떤 꿈이든 이미지로'],
    insights: ['나의 패턴 찾기', '반복되는 상징과 기분.\nFace ID로 잠금'],
  },
  'zh-Hans': {
    result: ['你的梦\n是什么意思？', 'AI 几秒钟为你解梦'],
    voice: ['醒来说一说就好', '语音或文字，\n每个梦都会保存'],
    interp: ['为你量身解读', '情绪、象征\n及其背后的寓意'],
    symbol: ['周公解梦\n覆盖每个象征', '300 多个梦境象征，\n另有荣格与民间解读'],
    chat: ['和露娜聊聊你的梦', '关于梦的任何问题都可以问'],
    image: ['看见你的梦', '把任何梦变成一幅画'],
    insights: ['发现你的规律', '反复出现的象征与情绪。\n私密，可用面容 ID 锁定'],
  },
  'zh-Hant': {
    result: ['你的夢\n代表什麼？', 'AI 幾秒就為你解夢'],
    voice: ['醒來說一說就好', '語音或文字，\n每個夢都會保存'],
    interp: ['為你量身解讀', '情緒、象徵\n及其背後的寓意'],
    symbol: ['周公解夢\n涵蓋每個象徵', '300 多個夢境象徵，\n也有榮格與民間解讀'],
    chat: ['和露娜聊聊你的夢', '關於夢的任何問題都可以問'],
    image: ['看見你的夢', '把任何夢變成一幅畫'],
    insights: ['發現你的規律', '反覆出現的象徵與情緒。\n私密，可用 Face ID 鎖定'],
  },
  // ── Indic: symbol frame on the Vedic tradition (स्वप्न शास्त्र) ─────────
  hi: {
    result: ['आपके सपने का क्या मतलब है?', 'AI से कुछ ही सेकंड में व्याख्या'],
    voice: ['जागते ही बता दीजिए', 'आवाज़ से या लिखकर — हर सपना सहेजा जाता है'],
    interp: ['सिर्फ़ आपके लिए व्याख्या', 'भावनाएँ, प्रतीक और उनका संदेश'],
    symbol: ['वैदिक स्वप्न शास्त्र से व्याख्या', '300+ प्रतीक — वैदिक, युंग और लोक परंपराएँ'],
    chat: ['लूना से बात कीजिए', 'अपने सपने के बारे में कुछ भी पूछें'],
    image: ['अपना सपना देखिए', 'किसी भी सपने को तस्वीर में बदलें'],
    insights: ['अपने पैटर्न पहचानिए', 'बार-बार आने वाले प्रतीक और मूड। निजी, Face ID लॉक'],
  },
  mr: {
    result: ['तुमच्या स्वप्नाचा अर्थ काय?', 'AI कडून काही सेकंदांत अर्थ'],
    voice: ['जाग येताच सांगा', 'आवाजाने किंवा लिहून — प्रत्येक स्वप्न जतन होते'],
    interp: ['खास तुमच्यासाठी अर्थ', 'भावना, प्रतीके आणि त्यांचा संदेश'],
    symbol: ['वैदिक स्वप्नशास्त्रानुसार अर्थ', '300+ प्रतीके — वैदिक, युंग आणि लोकपरंपरा'],
    chat: ['लूनाशी गप्पा मारा', 'तुमच्या स्वप्नाबद्दल काहीही विचारा'],
    image: ['तुमचे स्वप्न पाहा', 'कोणतेही स्वप्न चित्रात बदला'],
    insights: ['तुमचे पॅटर्न ओळखा', 'वारंवार येणारी प्रतीके आणि मूड. खाजगी, Face ID लॉक'],
  },
  gu: {
    result: ['તમારા સપનાનો અર્થ શું?', 'AI થી થોડી જ સેકન્ડમાં અર્થઘટન'],
    voice: ['જાગતાં જ કહી દો', 'અવાજથી કે લખીને — દરેક સપનું સચવાય છે'],
    interp: ['ફક્ત તમારા માટે અર્થઘટન', 'લાગણીઓ, પ્રતીકો અને તેમનો સંદેશ'],
    symbol: ['વૈદિક સ્વપ્નશાસ્ત્ર મુજબ અર્થ', '300+ પ્રતીકો — વૈદિક, યુંગ અને લોકપરંપરા'],
    chat: ['લૂના સાથે વાત કરો', 'તમારા સપના વિશે કંઈ પણ પૂછો'],
    image: ['તમારું સપનું જુઓ', 'કોઈપણ સપનાને ચિત્રમાં ફેરવો'],
    insights: ['તમારી પેટર્ન ઓળખો', 'વારંવાર આવતા પ્રતીકો અને મૂડ. ખાનગી, Face ID લૉક'],
  },
  kn: {
    result: ['ನಿಮ್ಮ ಕನಸಿನ ಅರ್ಥವೇನು?', 'AI ನಿಂದ ಕೆಲವೇ ಸೆಕೆಂಡುಗಳಲ್ಲಿ ವಿವರಣೆ'],
    voice: ['ಎಚ್ಚರವಾದ ತಕ್ಷಣ ಹೇಳಿ', 'ಧ್ವನಿ ಅಥವಾ ಬರಹ — ಪ್ರತಿಯೊಂದು ಕನಸು ಉಳಿಯುತ್ತದೆ'],
    interp: ['ನಿಮಗಾಗಿಯೇ ವಿವರಣೆ', 'ಭಾವನೆಗಳು, ಸಂಕೇತಗಳು ಮತ್ತು ಅವುಗಳ ಸಂದೇಶ'],
    symbol: ['ವೈದಿಕ ಸ್ವಪ್ನ ಶಾಸ್ತ್ರದ ಅರ್ಥ', '300+ ಸಂಕೇತಗಳು — ವೈದಿಕ, ಯುಂಗ್ ಮತ್ತು ಜಾನಪದ ಪರಂಪರೆ'],
    chat: ['ಲೂನಾ ಜೊತೆ ಮಾತನಾಡಿ', 'ನಿಮ್ಮ ಕನಸಿನ ಬಗ್ಗೆ ಏನು ಬೇಕಾದರೂ ಕೇಳಿ'],
    image: ['ನಿಮ್ಮ ಕನಸನ್ನು ನೋಡಿ', 'ಯಾವುದೇ ಕನಸನ್ನು ಚಿತ್ರವಾಗಿಸಿ'],
    insights: ['ನಿಮ್ಮ ಮಾದರಿಗಳನ್ನು ಕಂಡುಕೊಳ್ಳಿ', 'ಮರುಕಳಿಸುವ ಸಂಕೇತಗಳು ಮತ್ತು ಮನಸ್ಥಿತಿ. ಖಾಸಗಿ, Face ID ಲಾಕ್'],
  },
  ml: {
    result: ['സ്വപ്നത്തിന്റെ അർഥം?', 'AI ഏതാനും സെക്കൻഡിൽ വ്യാഖ്യാനിക്കും'],
    voice: ['ഉണർന്നയുടൻ പറയൂ', 'ശബ്ദമായോ എഴുതിയോ — ഓരോ സ്വപ്നവും സൂക്ഷിക്കും'],
    interp: ['നിങ്ങൾക്കായുള്ള വ്യാഖ്യാനം', 'വികാരങ്ങൾ, ചിഹ്നങ്ങൾ, അവയുടെ സന്ദേശം'],
    symbol: ['വൈദിക സ്വപ്നശാസ്ത്രം', '300+ ചിഹ്നങ്ങൾ — വൈദിക, യുങ്, നാടോടി പാരമ്പര്യങ്ങൾ'],
    chat: ['ലൂണയോട് സംസാരിക്കൂ', 'സ്വപ്നത്തെക്കുറിച്ച് എന്തും ചോദിക്കൂ'],
    image: ['നിങ്ങളുടെ സ്വപ്നം കാണൂ', 'ഏത് സ്വപ്നവും ചിത്രമാക്കൂ'],
    insights: ['ആവർത്തനങ്ങൾ കണ്ടെത്തൂ', 'ആവർത്തിക്കുന്ന ചിഹ്നങ്ങളും മനോഭാവങ്ങളും. സ്വകാര്യം, Face ID ലോക്ക്'],
  },
  or: {
    result: ['ଆପଣଙ୍କ ସ୍ୱପ୍ନର ଅର୍ଥ କ’ଣ?', 'AI ରୁ କିଛି ସେକେଣ୍ଡରେ ବ୍ୟାଖ୍ୟା'],
    voice: ['ଉଠିବା ମାତ୍ରେ କୁହନ୍ତୁ', 'ସ୍ୱର ବା ଲେଖା — ପ୍ରତ୍ୟେକ ସ୍ୱପ୍ନ ସଞ୍ଚିତ ରହେ'],
    interp: ['କେବଳ ଆପଣଙ୍କ ପାଇଁ ବ୍ୟାଖ୍ୟା', 'ଭାବନା, ପ୍ରତୀକ ଓ ସେମାନଙ୍କ ବାର୍ତ୍ତା'],
    symbol: ['ବୈଦିକ ସ୍ୱପ୍ନ ଶାସ୍ତ୍ର ଅନୁସାରେ', '300+ ପ୍ରତୀକ — ବୈଦିକ, ୟୁଙ୍ଗ ଓ ଲୋକ ପରମ୍ପରା'],
    chat: ['ଲୁନା ସହ କଥା ହୁଅନ୍ତୁ', 'ଆପଣଙ୍କ ସ୍ୱପ୍ନ ବିଷୟରେ ଯାହା ବି ପଚାରନ୍ତୁ'],
    image: ['ଆପଣଙ୍କ ସ୍ୱପ୍ନ ଦେଖନ୍ତୁ', 'ଯେକୌଣସି ସ୍ୱପ୍ନକୁ ଚିତ୍ରରେ ବଦଳାନ୍ତୁ'],
    insights: ['ଆପଣଙ୍କ ପ୍ୟାଟର୍ନ ଚିହ୍ନନ୍ତୁ', 'ବାରମ୍ବାର ଆସୁଥିବା ପ୍ରତୀକ ଓ ମନୋଭାବ। ବ୍ୟକ୍ତିଗତ, Face ID ଲକ୍'],
  },
  pa: {
    result: ['ਤੁਹਾਡੇ ਸੁਪਨੇ ਦਾ ਕੀ ਅਰਥ ਹੈ?', 'AI ਨਾਲ ਕੁਝ ਹੀ ਸਕਿੰਟਾਂ ਵਿੱਚ ਵਿਆਖਿਆ'],
    voice: ['ਜਾਗਦੇ ਹੀ ਦੱਸ ਦਿਓ', 'ਆਵਾਜ਼ ਜਾਂ ਲਿਖਤ — ਹਰ ਸੁਪਨਾ ਸੰਭਾਲਿਆ ਜਾਂਦਾ ਹੈ'],
    interp: ['ਸਿਰਫ਼ ਤੁਹਾਡੇ ਲਈ ਵਿਆਖਿਆ', 'ਭਾਵਨਾਵਾਂ, ਪ੍ਰਤੀਕ ਅਤੇ ਉਨ੍ਹਾਂ ਦਾ ਸੁਨੇਹਾ'],
    symbol: ['ਵੈਦਿਕ ਸੁਪਨ ਸ਼ਾਸਤਰ ਅਨੁਸਾਰ', '300+ ਪ੍ਰਤੀਕ — ਵੈਦਿਕ, ਯੁੰਗ ਅਤੇ ਲੋਕ ਪਰੰਪਰਾਵਾਂ'],
    chat: ['ਲੂਨਾ ਨਾਲ ਗੱਲ ਕਰੋ', 'ਆਪਣੇ ਸੁਪਨੇ ਬਾਰੇ ਕੁਝ ਵੀ ਪੁੱਛੋ'],
    image: ['ਆਪਣਾ ਸੁਪਨਾ ਦੇਖੋ', 'ਕਿਸੇ ਵੀ ਸੁਪਨੇ ਨੂੰ ਤਸਵੀਰ ਵਿੱਚ ਬਦਲੋ'],
    insights: ['ਆਪਣੇ ਪੈਟਰਨ ਲੱਭੋ', 'ਵਾਰ-ਵਾਰ ਆਉਣ ਵਾਲੇ ਪ੍ਰਤੀਕ ਅਤੇ ਮੂਡ। ਨਿੱਜੀ, Face ID ਲੌਕ'],
  },
  ta: {
    result: ['கனவின் அர்த்தம் என்ன?', 'AI சில நொடிகளில் விளக்கம் தரும்'],
    voice: ['விழித்ததும் சொல்லுங்கள்', 'குரலிலோ எழுத்திலோ — ஒவ்வொரு கனவும் சேமிக்கப்படும்'],
    interp: ['உங்களுக்கான விளக்கம்', 'உணர்வுகள், குறியீடுகள், அவற்றின் செய்தி'],
    symbol: ['வேத கனவு விளக்கம்', '300+ குறியீடுகள் — வேத, யுங், நாட்டுப்புற மரபுகள்'],
    chat: ['லூனாவுடன் பேசுங்கள்', 'உங்கள் கனவு பற்றி எதையும் கேளுங்கள்'],
    image: ['கனவைப் பாருங்கள்', 'எந்தக் கனவையும் படமாக மாற்றுங்கள்'],
    insights: ['வடிவங்களைக் கண்டறியுங்கள்', 'மீண்டும் வரும் குறியீடுகளும் மனநிலைகளும். தனிப்பட்டது, Face ID பூட்டு'],
  },
  te: {
    result: ['మీ కల అర్థం ఏమిటి?', 'AI కొన్ని సెకన్లలో వివరణ ఇస్తుంది'],
    voice: ['మేల్కొనగానే చెప్పండి', 'గొంతుతో లేదా రాతతో — ప్రతి కల భద్రంగా ఉంటుంది'],
    interp: ['మీ కోసమే వివరణ', 'భావాలు, సంకేతాలు, వాటి సందేశం'],
    symbol: ['వైదిక స్వప్న శాస్త్ర వివరణ', '300+ సంకేతాలు — వైదిక, యుంగ్, జానపద సంప్రదాయాలు'],
    chat: ['లూనాతో మాట్లాడండి', 'మీ కల గురించి ఏదైనా అడగండి'],
    image: ['మీ కలను చూడండి', 'ఏ కలనైనా చిత్రంగా మార్చండి'],
    insights: ['మీ నమూనాలను కనుగొనండి', 'పదే పదే వచ్చే సంకేతాలు, మూడ్‌లు. ప్రైవేట్, Face ID లాక్'],
  },
};

/** ASC store locale → copy language above. */
export const LOCALE_COPY = {
  'en-US': 'en', 'en-GB': 'en', 'en-AU': 'en', 'en-CA': 'en',
  'es-ES': 'es', 'es-MX': 'es', 'fr-FR': 'fr', 'fr-CA': 'fr', 'de-DE': 'de',
  'nl-NL': 'nl', 'ar-SA': 'ar', 'bn-BD': 'bn', 'ur-PK': 'ur',
  'gu-IN': 'gu', 'kn-IN': 'kn', 'ml-IN': 'ml', 'mr-IN': 'mr', 'or-IN': 'or',
  'pa-IN': 'pa', 'ta-IN': 'ta', 'te-IN': 'te',
};

/** Locales whose symbol/tradition frame moves to position 2 (vault §8). */
export const TRADITION_FIRST = ['ar-SA', 'tr', 'ur-PK', 'id', 'ms', 'bn-BD'];
